server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-63954939.okta.com/oauth2/default
    client-id: 0oa7451v81v4EeUIE5d7
    client-secret: p5OyBKFMohHIzfjKPdPUb5lk9fdsr_iuwH7IxHUq
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka
spring:
   application:
      name: graph-service
   data:
      neo4j: 
         uri: bolt://localhost:7687
         username: neo4j
         password: RB2383tkp!
   cloud: 
      stream:
         function:
           definition: userEventConsumer
         bindings:
           userEventConsumer-in-0:
              destination: user-event
         kafka:
           bindings:
             userEventConsumer-in-0:
               consumer:
                 configuration:
                   value:
                     deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer   
      