server:
  port: 8080
okta:
  oauth2:
    issuer: ${OKTA_ISSUER}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
spring:
   application:
      name: graph-service
   data:
      neo4j: 
         uri: ${NEO4J_DATABASE_CONNECTION}
         username: ${NEO4J_USER}
         password: ${NEO4J_PASSWORD}
   cloud: 
      stream:
         function:
           definition: userEventConsumer
         bindings:
           userEventConsumer-in-0:
              destination: user-event
         kafka:
           bindings:
             userEventConsumer-in-0:
               consumer:
                 configuration:
                   value:
                     deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer   
      